 export const fakeData = [
    { id: 1, title: 'Job1', location: 'Location1', companyName: 'Company1', salary: 10000, description: 'Description', employmentType: 'full-time' },
    { id: 2, title: 'Job2', location: 'Location2', companyName: 'Company2', salary: 20000, description: 'Description', employmentType: 'part-time'},
    { id: 3, title: 'Job3', location: 'Location3', companyName: 'Company3', salary: 30000, description: 'Description', employmentType: 'contract' },
    { id: 4, title: 'Job4', location: 'Location4', companyName: 'Company4', salary: 4000, description: 'Description', employmentType: 'internship' },
    { id: 5, title: 'Job5', location: 'Location5', companyName: 'Company5', salary: 500, description: 'Description', employmentType: 'full-time' },
    { id: 6, title: 'Job6', location: 'Location6', companyName: 'Company6', salary: 600,    description: 'Description', employmentType: 'part-time' },
    { id: 7, title: 'Job7', location: 'Location7', companyName: 'Company7', salary: 700,   description: 'Description', employmentType: 'contract' },
    { id: 8, title: 'Job8', location: 'Location8', companyName: 'Company8', salary: 800, description: 'Description', employmentType: 'internship'},
    { id: 9, title: 'Job9', location: 'Location9', companyName: 'Company9', salary: 900, description: 'Description', employmentType: 'full-time' },
    { id: 10, title: 'Job10', location: 'Location10', companyName: 'Company10', salary: 1000, description: 'Description', employmentType: 'part-time' },
    { id: 11, title: 'Job11', location: 'Location11', companyName: 'Company11', salary: 1100, description: 'Description', employmentType: 'contract' },
    { id: 12, title: 'Job12', location: 'Location12', companyName: 'Company12', salary: 1200, description: 'Description', employmentType: 'internship' },
    { id: 13, title: 'Job13', location: 'Location13', companyName: 'Company13', salary: 1300, description: 'Description', employmentType: 'full-time' },
    { id: 14, title: 'Job14', location: 'Location14', companyName: 'Company14', salary: 1400, description: 'Description', employmentType: 'part-time' },
    { id: 15, title: 'Job15', location: 'Location15', companyName: 'Company15', salary: 1500, description: 'Description', employmentType: 'contract' },
    { id: 16, title: 'Job16', location: 'Location16', companyName: 'Company16', salary: 1600, description: 'Description', employmentType: 'internship' },
    { id: 17, title: 'Job17', location: 'Location17', companyName: 'Company17', salary: 1700, description: 'Description', employmentType: 'full-time' },
    { id: 18, title: 'Job18', location: 'Location18', companyName: 'Company18', salary: 1800, description: 'Description', employmentType: 'part-time' },
    { id: 19, title: 'Job19', location: 'Location19', companyName: 'Company19', salary: 1900, description: 'Description', employmentType: 'contract' },
    { id: 20, title: 'Job20', location: 'Location20', companyName: 'Company20', salary: 2000, description: 'Description', employmentType: 'internship' },
    { id: 21, title: 'Job21', location: 'Location21', companyName: 'Company21', salary: 2100, description: 'Description', employmentType: 'full-time' },
    { id: 22, title: 'Job22', location: 'Location22', companyName: 'Company22', salary: 2200, description: 'Description', employmentType: 'part-time' },
    { id: 23, title: 'Job23', location: 'Location23', companyName: 'Company23', salary: 2300, description: 'Description', employmentType: 'contract' },
    { id: 24, title: 'Job24', location: 'Location24', companyName: 'Company24', salary: 2400, description: 'Description', employmentType: 'internship' },
    { id: 25, title: 'Job25', location: 'Location25'},
];