export const locations = [
    'Remote',
    'Warsaw',
    'Oslo',
    'Krakow',
    'Drammen',
    'Poznan',
    'Wroclaw',
    'Gdansk',
    'Gdynia',
    'Sopot',
];

export const positions = [
    'Backend',
    'Frontend',
    'Fullstack',
    'Devops',
    'QA',
    'UX',
    'UI',
    'Product',
    'Project',
    'Analyst',
    'Security',
    'Network',
    'Cloud',
    'Mobile',
    'Hardware',
    'Embedded',
    'Game',
    'Blockchain',
    'Machine learning',
    'Artificial intelligence',
    'Cybersecurity',
    'Ethical hacking',
];

export const technologies: string[] = [
    'HTML',
    'CSS3',
    'JavaScript',
    'React',
    'Node.js',
    'Express',
    'MongoDB',
    'Python',
    'Django',
    'Flask',
    'PostgreSQL',
    'Ruby',
    'Rails',
    'Java',
    'Spring',
    'MySQL',
    'C#',
    'C++',
    'C',
    'Swift',
    'Kotlin',
    'Go',
    'Rust',
    'TypeScript',
    'Vue.js',
    'Angular',
    'Svelte',
    'PHP',
    'Laravel',
    'Symfony',
    'WordPress',
    'Drupal',
    'Joomla',
    'Magento',
    'Shopify',
    'WooCommerce',
    'Wix',
    'Webflow',
    'GraphQL',
    'REST',
    'API',
    'OAuth',
    'Docker',
    'Kubernetes',
    'Jenkins',
    'Kubernetes',
];
